### ISSUE TITLE
get_mysql_table_records() got an unexpected keyword argument 'form_name'

### ISSUE THREAD

**Issue by shippy** [sibis-platform/sibispy#15]
Likely an artifact of the update to RC8. Will investigate later.

```
ncanda@ncanda-storage:pipeline-back-1.4:/sibis-software/python-packages/sibispy/cmds$ ./exec_redcap_locking_data.py -f mri_stroop,mr_session_report -e "3y visit" -s E-00361-M-3 --verbose --unlock
Connected to REDCap using: Engine(mysql+pymysql://root:***@192.168.1.1:3306/redcap)
Visit: 3y visit
Attempting to unlock form: mri_stroop,mr_session_report
Traceback (most recent call last):
  File "./exec_redcap_locking_data.py", line 123, in <module>
    sys.exit(main(args=args))
  File "./exec_redcap_locking_data.py", line 64, in main
    if not red_lock.unlock_form(args.project, args.arm, event_desc, args.form, subject_id = sid):
  File "/sibis-software/python-packages/sibispy/redcap_locking_data.py", line 32, in unlock_form
    locked_forms = self.__session__.get_mysql_table_records('redcap_locking_data', project_name, arm_name, event_descrip,form_name = name_of_form, subject_id = subject_id)
TypeError: get_mysql_table_records() got an unexpected keyword argument 'form_name'
```

**Comment by shippy** [comment]
Verified:

```
ncanda@ncanda-storage[pipeline-interactive]:/sibis-software/python-packages/sibispy/cmds (master)$ ./exec_redcap_locking_data.py -f mri_stroop -e "3y visit" -s E-00361-M-3 --unlock --verbose                       
Connected to REDCap using: Engine(mysql+pymysql://root:***@192.168.1.1:3306/redcap)
Visit: 3y visit
Attempting to unlock form: mri_stroop
The mri_stroop form has been unlocked
Done!
ncanda@ncanda-storage[pipeline-interactive]:/sibis-software/python-packages/sibispy/cmds (master)$ ./exec_redcap_locking_data.py -f mr_session_report -e "3y visit" -s E-00361-M-3 --unlock --verbose                
Connected to REDCap using: Engine(mysql+pymysql://root:***@192.168.1.1:3306/redcap)
Visit: 3y visit
Attempting to unlock form: mr_session_report
The mr_session_report form has been unlocked
Done!
ncanda@ncanda-storage[pipeline-interactive]:/sibis-software/python-packages/sibispy/cmds (master)$ ./exec_redcap_locking_data.py -f mr_session_report -e "3y visit" -s E-00361-M-3 --lock --verbose                  
Connected to REDCap using: Engine(mysql+pymysql://root:***@192.168.1.1:3306/redcap)
Visit: 3y visit
Attempting to lock form: mr_session_report
The mr_session_report form has been locked
Record of locked files: /tmp/locked_records.csv
Done!
ncanda@ncanda-storage[pipeline-interactive]:/sibis-software/python-packages/sibispy/cmds (master)$ ./exec_redcap_locking_data.py -f mri_stroop -e "3y visit" -s E-00361-M-3 --lock --verbose                         
Connected to REDCap using: Engine(mysql+pymysql://root:***@192.168.1.1:3306/redcap)
Visit: 3y visit
Attempting to lock form: mri_stroop
The mri_stroop form has been locked
Record of locked files: /tmp/locked_records.csv
Done!
```
